import localFont from "next/font/local";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "./_providers/AuthProvider";
import { connectMongoDB } from "@/dbConnect/connectMongo";
import { ToastContainer } from "react-toastify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 async  function RootLayout({ children }) {
  await connectMongoDB()
  
  return (
    <AuthProvider>
      <html lang="en">
        <body className="bg-black text-white">
          <link rel="stylesheet" href="/styles/output.css" />
          <ToastContainer />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
export default RootLayout
