import Navbar from "@/app/components/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SingleMovieLayout({ children }) {
  return (
    <>
      <Navbar />
      {children}
    </>
  );
}
